## Hannah Melcher
## CS-150-01
## Version 1
## PA8

### A

In [2]:
import numpy as np

# 2-by-2 numpy array
arr = np.array([[10, 20], [30, 40]])

# square every element of the array
squared = arr ** 2
print("Squared array:\n", squared)

# add 100 to every element of the array
added = arr + 100
print("Added array:\n", added)

# multiply every element of the array by 5
multiplied = arr * 5
print("Multiplied array:\n", multiplied)

# calculate the square root of each element in the array
sqrt = np.sqrt(arr)
print("Square root array:\n", sqrt)

Squared array:
 [[ 100  400]
 [ 900 1600]]
Added array:
 [[110 120]
 [130 140]]
Multiplied array:
 [[ 50 100]
 [150 200]]
Square root array:
 [[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


### B

In [3]:
import numpy as np

# 3-by-3 array containing integers from 3 to 27 in multiples of 3
arr1 = np.arange(3, 30, 3).reshape(3, 3)
print("Array 1:\n", arr1)

# second 3-by-3 array with 9 elements evenly spaced between 10 and 20
arr2 = np.linspace(10, 20, 9).reshape(3, 3)
print("Array 2:\n", arr2)

# multiply the two arrays
product = arr1 * arr2
print("Product:\n", product)

Array 1:
 [[ 3  6  9]
 [12 15 18]
 [21 24 27]]
Array 2:
 [[10.   11.25 12.5 ]
 [13.75 15.   16.25]
 [17.5  18.75 20.  ]]
Product:
 [[ 30.   67.5 112.5]
 [165.  225.  292.5]
 [367.5 450.  540. ]]


### C

In [5]:
process1=np.load('process1.npy')
process2=np.load('process2.npy')
process3=np.load('process3.npy')
process4=np.load('process4.npy')
process5=np.load('process5.npy')

In [6]:
Data=np.stack([process1,process2,process3,process4,process5])
print(Data)

[[[52 12 81  0 58]]

 [[96  4 61 16 43]]

 [[38 96 45 17 58]]

 [[97 21 22 25  6]]

 [[77  6 19  2 74]]]


In [7]:
Mean=np.mean(Data, axis=0)
print(Mean)

[[72.  27.8 45.6 12.  47.8]]
